apiVersion: apps/v1
kind: Deployment
metadata:
  name: grono-youtube-seo
  labels:
    app: grono-youtube-seo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grono-youtube-seo
  template:
    metadata:
      labels:
        app: grono-youtube-seo
    spec:
      containers:
      - name: webapp
        image: 460783431753.dkr.ecr.ap-south-1.amazonaws.com/grono-youtube-seo:BUILD_NUMBER
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
       env:
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: youtube-api-secret
                  key: YOUTUBE_API_KEY

            - name: FLASK_ENV
              value: "production"
